server:
  port: 8000

spring:
  profiles:
    active: dev # 开发环境
    include: feign # 引入feign配置
  application:
      name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false # 禁用nacos配置导入检查
        namespace: ${spring.profiles.active:dev}
  config:
    import:
      - nacos:common.yaml?group=order_group # yaml与yml都可以，社区yml多，先导入优先与外部优先
      - nacos:database.yaml?group=order_group # yaml与yml都可以，社区yml多，先导入优先与外部优先

logging:
  level:
    com.learning.order.feign: debug


order:
  timeout: 30m
  auto-confirm: 7d测试 # 当项目与配置中心有相同配置，以配置中心为准，

# 配置文件,不同环境，不同配置文件
---
spring:
  config:
    import:
      - nacos:common.yaml?group=order_group
      - nacos:database.yaml?group=order_group
      - nacos:1.yaml?group=order_group
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.yaml?group=order_group
      - nacos:database.yaml?group=order_group
      - nacos:2.yaml?group=order_group
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.yaml?group=order_group
      - nacos:database.yaml?group=order_group
      - nacos:3.yaml?group=order_group
      - nacos:4.yaml?group=order_group
    activate:
      on-profile: prod

